#端口号
server:
  port: 10000
#服务名称
spring:
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.208.16:3306/elec_mall?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 83677629
  redis:
    host: 47.100.208.16
    port: 6379
    password: 83677629
    database: 0
    timeout: 1800000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#配置mapper地址

#logback配置文件地址
logging:
  config: logback-dev.xml