#端口号
server:
  port: 10000
#服务名称
spring:
  application:
    name:
    # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elec_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 83677629
  redis:
    host: 47.100.208.16
    port: 6379
    password: 83677629
    database: 0
    timeout: 1800000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.208.16:3306:8848
#配置mapper地址
logging:
  config: classpath:/logback-dev.xml