#端口号
server:
  port: 10000
#服务名称
spring:
  application:
    name: gateway
    # mysql数据库连接
  redis:
    host: 47.100.208.16
    port: 6379
    password: 83677629
    database: 0
    timeout: 1800000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 47.100.208.16:3306:8848
#配置mapper地址
